algo: "fedpart"
problem: "vision"

#task:
n_rounds: 1000
dataset: "cifar10"
dist: "NON-IID" # IID, NON-IID, ONE, TWO
pholder: [1, 32, 32, 3]
num_classes: 10
parts: 200
#train:
batch_size: 128
opt_name: "sgd"
lr: 0.0322330043229846
momentum: 0.392581313218887
client_epoch: 20
n_clients: 5

network_name: "CNN"
network_config:
  depth_1: 1
  depth_2: 2
  features_1: 64
  features_2: 128
  kernel_1: 5
  kernel_2: 5
  strides_1: 1
  strides_2: 1
  num_linear_layers: 1
  num_hidden_units: 256
  num_output_units: 10

#es
strategy: "OpenES"
#batch_size: 64
pop_size: 32
#opt_name: "adam"
sigma_init: 0.4204310687298901
sigma_decay: 1.0019802260149069
sigma_limit: 0.01
init_min: 0.0
init_max: 0.0
clip_min: -10
clip_max: 10

lrate_init: 0.04668448315837
lrate_decay: 1
lrate_limit: 0.001
beta_1: 0.99
beta_2: 0.999
eps: 1e-8
momentum_es: 0.4792644986366237


#fitness
maximize: true
centered_rank: true
z_score: true
w_decay: 0.06916494977445797


#device:
num_devices: 1
device_type: "gpu"