algo: "fedpart"
problem: "vision"


n_rounds: 500
dataset: "cifar10"
dist: "NON-IID" # IID, NON-IID, ONE, TWO
pholder: [1, 32, 32, 3]
num_classes: 10
n_clients: 5
parts: 100
#train:
batch_size: 128
opt_name: "sgd"
lr: 0.02788345962373156
momentum: 0.2775090330310499
client_epoch: 10

network_name: "ResNet"
network_config:
  num_blocks: 2
  features: [32, 32]
  kernel_size: 5
  strides: 1
  num_output_units: 10


#task:
#n_rounds: 1000
#dataset: "cifar10"
#dist: "NON-IID" # IID, NON-IID, ONE, TWO
#pholder: [1, 32, 32, 3]
#num_classes: 10
#parts: 100
#n_clients: 5
#
##train:
#batch_size: 64
#opt_name: "sgd"
#lr: 0.014844104496041774
#momentum: 0.3010756890317885
#client_epoch: 1
#
#
#network_name: "CNN"
#network_config:
#  depth_1: 1
#  depth_2: 1
#  features_1: 64
#  features_2: 128
#  kernel_1: 5
#  kernel_2: 5
#  strides_1: 1
#  strides_2: 1
#  num_linear_layers: 1
#  num_hidden_units: 256
#  num_output_units: 10

#es
strategy: "OpenES"
#batch_size: 64
pop_size: 32
#opt_name: "adam"
sigma_init: 0.34281529026502133
sigma_decay: 1.0052091049237892
sigma_limit: 0.01
init_min: 0.0
init_max: 0.0
clip_min: -10
clip_max: 10

lrate_init: 0.027501627466751888
lrate_decay: 1
lrate_limit: 0.001
beta_1: 0.99
beta_2: 0.999
eps: 1e-8
momentum_es: 0.5238616883771412


#fitness
maximize: true
centered_rank: false
z_score: true
w_decay: 0.08238013032804412
